# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(450, 830)
        self.frame2 = QtGui.QFrame(Dialog)
        self.frame2.setGeometry(QtCore.QRect(10, 150, 431, 241))
        self.frame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame2.setObjectName(_fromUtf8("frame2"))
        self.label2 = QtGui.QLabel(self.frame2)
        self.label2.setGeometry(QtCore.QRect(180, 0, 61, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.cb_sinsa = QtGui.QCheckBox(self.frame2)
        self.cb_sinsa.setGeometry(QtCore.QRect(10, 30, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_sinsa.setFont(font)
        self.cb_sinsa.setObjectName(_fromUtf8("cb_sinsa"))
        self.cb_gangnam = QtGui.QCheckBox(self.frame2)
        self.cb_gangnam.setGeometry(QtCore.QRect(10, 50, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_gangnam.setFont(font)
        self.cb_gangnam.setObjectName(_fromUtf8("cb_gangnam"))
        self.cb_geondae = QtGui.QCheckBox(self.frame2)
        self.cb_geondae.setGeometry(QtCore.QRect(10, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_geondae.setFont(font)
        self.cb_geondae.setObjectName(_fromUtf8("cb_geondae"))
        self.cb_nowon = QtGui.QCheckBox(self.frame2)
        self.cb_nowon.setGeometry(QtCore.QRect(10, 90, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_nowon.setFont(font)
        self.cb_nowon.setObjectName(_fromUtf8("cb_nowon"))
        self.cb_daehakro = QtGui.QCheckBox(self.frame2)
        self.cb_daehakro.setGeometry(QtCore.QRect(10, 110, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_daehakro.setFont(font)
        self.cb_daehakro.setObjectName(_fromUtf8("cb_daehakro"))
        self.cb_suyu = QtGui.QCheckBox(self.frame2)
        self.cb_suyu.setGeometry(QtCore.QRect(10, 130, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_suyu.setFont(font)
        self.cb_suyu.setObjectName(_fromUtf8("cb_suyu"))
        self.cb_sillim = QtGui.QCheckBox(self.frame2)
        self.cb_sillim.setGeometry(QtCore.QRect(10, 150, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_sillim.setFont(font)
        self.cb_sillim.setObjectName(_fromUtf8("cb_sillim"))
        self.cb_sinchon = QtGui.QCheckBox(self.frame2)
        self.cb_sinchon.setGeometry(QtCore.QRect(10, 170, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_sinchon.setFont(font)
        self.cb_sinchon.setObjectName(_fromUtf8("cb_sinchon"))
        self.cb_yeonsinnae = QtGui.QCheckBox(self.frame2)
        self.cb_yeonsinnae.setGeometry(QtCore.QRect(10, 190, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_yeonsinnae.setFont(font)
        self.cb_yeonsinnae.setObjectName(_fromUtf8("cb_yeonsinnae"))
        self.cb_jamsil = QtGui.QCheckBox(self.frame2)
        self.cb_jamsil.setGeometry(QtCore.QRect(10, 210, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_jamsil.setFont(font)
        self.cb_jamsil.setObjectName(_fromUtf8("cb_jamsil"))
        self.cb_sincheon = QtGui.QCheckBox(self.frame2)
        self.cb_sincheon.setGeometry(QtCore.QRect(110, 30, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_sincheon.setFont(font)
        self.cb_sincheon.setObjectName(_fromUtf8("cb_sincheon"))
        self.cb_ilsan = QtGui.QCheckBox(self.frame2)
        self.cb_ilsan.setGeometry(QtCore.QRect(230, 30, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_ilsan.setFont(font)
        self.cb_ilsan.setObjectName(_fromUtf8("cb_ilsan"))
        self.cb_dongbo = QtGui.QCheckBox(self.frame2)
        self.cb_dongbo.setGeometry(QtCore.QRect(340, 30, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_dongbo.setFont(font)
        self.cb_dongbo.setObjectName(_fromUtf8("cb_dongbo"))
        self.cb_jongno = QtGui.QCheckBox(self.frame2)
        self.cb_jongno.setGeometry(QtCore.QRect(110, 50, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_jongno.setFont(font)
        self.cb_jongno.setObjectName(_fromUtf8("cb_jongno"))
        self.cb_hapjeong = QtGui.QCheckBox(self.frame2)
        self.cb_hapjeong.setGeometry(QtCore.QRect(110, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_hapjeong.setFont(font)
        self.cb_hapjeong.setObjectName(_fromUtf8("cb_hapjeong"))
        self.cb_dongtan = QtGui.QCheckBox(self.frame2)
        self.cb_dongtan.setGeometry(QtCore.QRect(110, 90, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_dongtan.setFont(font)
        self.cb_dongtan.setObjectName(_fromUtf8("cb_dongtan"))
        self.cb_bucheon = QtGui.QCheckBox(self.frame2)
        self.cb_bucheon.setGeometry(QtCore.QRect(110, 110, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_bucheon.setFont(font)
        self.cb_bucheon.setObjectName(_fromUtf8("cb_bucheon"))
        self.cb_bundang = QtGui.QCheckBox(self.frame2)
        self.cb_bundang.setGeometry(QtCore.QRect(110, 150, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_bundang.setFont(font)
        self.cb_bundang.setObjectName(_fromUtf8("cb_bundang"))
        self.cb_yatap = QtGui.QCheckBox(self.frame2)
        self.cb_yatap.setGeometry(QtCore.QRect(110, 170, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_yatap.setFont(font)
        self.cb_yatap.setObjectName(_fromUtf8("cb_yatap"))
        self.cb_sanbon = QtGui.QCheckBox(self.frame2)
        self.cb_sanbon.setGeometry(QtCore.QRect(110, 130, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_sanbon.setFont(font)
        self.cb_sanbon.setObjectName(_fromUtf8("cb_sanbon"))
        self.cb_suwon = QtGui.QCheckBox(self.frame2)
        self.cb_suwon.setGeometry(QtCore.QRect(110, 190, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_suwon.setFont(font)
        self.cb_suwon.setObjectName(_fromUtf8("cb_suwon"))
        self.cb_hwajeong = QtGui.QCheckBox(self.frame2)
        self.cb_hwajeong.setGeometry(QtCore.QRect(230, 50, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_hwajeong.setFont(font)
        self.cb_hwajeong.setObjectName(_fromUtf8("cb_hwajeong"))
        self.cb_sangmu = QtGui.QCheckBox(self.frame2)
        self.cb_sangmu.setGeometry(QtCore.QRect(230, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_sangmu.setFont(font)
        self.cb_sangmu.setObjectName(_fromUtf8("cb_sangmu"))
        self.cb_gwangju = QtGui.QCheckBox(self.frame2)
        self.cb_gwangju.setGeometry(QtCore.QRect(230, 90, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_gwangju.setFont(font)
        self.cb_gwangju.setObjectName(_fromUtf8("cb_gwangju"))
        self.cb_daegu = QtGui.QCheckBox(self.frame2)
        self.cb_daegu.setGeometry(QtCore.QRect(230, 110, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_daegu.setFont(font)
        self.cb_daegu.setObjectName(_fromUtf8("cb_daegu"))
        self.cb_sangin = QtGui.QCheckBox(self.frame2)
        self.cb_sangin.setGeometry(QtCore.QRect(230, 130, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_sangin.setFont(font)
        self.cb_sangin.setObjectName(_fromUtf8("cb_sangin"))
        self.cb_daejeoncityhall = QtGui.QCheckBox(self.frame2)
        self.cb_daejeoncityhall.setGeometry(QtCore.QRect(230, 150, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_daejeoncityhall.setFont(font)
        self.cb_daejeoncityhall.setObjectName(_fromUtf8("cb_daejeoncityhall"))
        self.cb_daejeon = QtGui.QCheckBox(self.frame2)
        self.cb_daejeon.setGeometry(QtCore.QRect(230, 170, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_daejeon.setFont(font)
        self.cb_daejeon.setObjectName(_fromUtf8("cb_daejeon"))
        self.cb_killy = QtGui.QCheckBox(self.frame2)
        self.cb_killy.setGeometry(QtCore.QRect(230, 210, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_killy.setFont(font)
        self.cb_killy.setObjectName(_fromUtf8("cb_killy"))
        self.cb_centum = QtGui.QCheckBox(self.frame2)
        self.cb_centum.setGeometry(QtCore.QRect(340, 50, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_centum.setFont(font)
        self.cb_centum.setObjectName(_fromUtf8("cb_centum"))
        self.cb_ulsan = QtGui.QCheckBox(self.frame2)
        self.cb_ulsan.setGeometry(QtCore.QRect(340, 90, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_ulsan.setFont(font)
        self.cb_ulsan.setObjectName(_fromUtf8("cb_ulsan"))
        self.cb_gyesan = QtGui.QCheckBox(self.frame2)
        self.cb_gyesan.setGeometry(QtCore.QRect(230, 190, 131, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_gyesan.setFont(font)
        self.cb_gyesan.setObjectName(_fromUtf8("cb_gyesan"))
        self.cb_jeonju = QtGui.QCheckBox(self.frame2)
        self.cb_jeonju.setGeometry(QtCore.QRect(340, 110, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_jeonju.setFont(font)
        self.cb_jeonju.setObjectName(_fromUtf8("cb_jeonju"))
        self.cb_cheonan = QtGui.QCheckBox(self.frame2)
        self.cb_cheonan.setGeometry(QtCore.QRect(340, 130, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_cheonan.setFont(font)
        self.cb_cheonan.setObjectName(_fromUtf8("cb_cheonan"))
        self.cb_cheongju = QtGui.QCheckBox(self.frame2)
        self.cb_cheongju.setGeometry(QtCore.QRect(340, 150, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_cheongju.setFont(font)
        self.cb_cheongju.setObjectName(_fromUtf8("cb_cheongju"))
        self.cb_guwol = QtGui.QCheckBox(self.frame2)
        self.cb_guwol.setGeometry(QtCore.QRect(340, 170, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_guwol.setFont(font)
        self.cb_guwol.setObjectName(_fromUtf8("cb_guwol"))
        self.cb_deokcheon = QtGui.QCheckBox(self.frame2)
        self.cb_deokcheon.setGeometry(QtCore.QRect(340, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_deokcheon.setFont(font)
        self.cb_deokcheon.setObjectName(_fromUtf8("cb_deokcheon"))
        self.cb_buksuwon = QtGui.QCheckBox(self.frame2)
        self.cb_buksuwon.setGeometry(QtCore.QRect(110, 210, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_buksuwon.setFont(font)
        self.cb_buksuwon.setObjectName(_fromUtf8("cb_buksuwon"))
        self.frame3 = QtGui.QFrame(Dialog)
        self.frame3.setGeometry(QtCore.QRect(10, 390, 431, 221))
        self.frame3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame3.setObjectName(_fromUtf8("frame3"))
        self.label3 = QtGui.QLabel(self.frame3)
        self.label3.setGeometry(QtCore.QRect(150, 0, 131, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.cb_1230 = QtGui.QCheckBox(self.frame3)
        self.cb_1230.setGeometry(QtCore.QRect(10, 40, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_1230.setFont(font)
        self.cb_1230.setObjectName(_fromUtf8("cb_1230"))
        self.cb_2551 = QtGui.QCheckBox(self.frame3)
        self.cb_2551.setGeometry(QtCore.QRect(150, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_2551.setFont(font)
        self.cb_2551.setObjectName(_fromUtf8("cb_2551"))
        self.cb_1108 = QtGui.QCheckBox(self.frame3)
        self.cb_1108.setGeometry(QtCore.QRect(300, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_1108.setFont(font)
        self.cb_1108.setObjectName(_fromUtf8("cb_1108"))
        self.cb_656 = QtGui.QCheckBox(self.frame3)
        self.cb_656.setGeometry(QtCore.QRect(10, 60, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_656.setFont(font)
        self.cb_656.setObjectName(_fromUtf8("cb_656"))
        self.cb_4395 = QtGui.QCheckBox(self.frame3)
        self.cb_4395.setGeometry(QtCore.QRect(10, 80, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_4395.setFont(font)
        self.cb_4395.setObjectName(_fromUtf8("cb_4395"))
        self.cb_351 = QtGui.QCheckBox(self.frame3)
        self.cb_351.setGeometry(QtCore.QRect(10, 100, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_351.setFont(font)
        self.cb_351.setObjectName(_fromUtf8("cb_351"))
        self.cb_1196 = QtGui.QCheckBox(self.frame3)
        self.cb_1196.setGeometry(QtCore.QRect(10, 120, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_1196.setFont(font)
        self.cb_1196.setObjectName(_fromUtf8("cb_1196"))
        self.cb_1 = QtGui.QCheckBox(self.frame3)
        self.cb_1.setGeometry(QtCore.QRect(10, 140, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_1.setFont(font)
        self.cb_1.setObjectName(_fromUtf8("cb_1"))
        self.cb_987 = QtGui.QCheckBox(self.frame3)
        self.cb_987.setGeometry(QtCore.QRect(10, 160, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_987.setFont(font)
        self.cb_987.setObjectName(_fromUtf8("cb_987"))
        self.cb_50246 = QtGui.QCheckBox(self.frame3)
        self.cb_50246.setGeometry(QtCore.QRect(150, 60, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_50246.setFont(font)
        self.cb_50246.setObjectName(_fromUtf8("cb_50246"))
        self.cb_13789 = QtGui.QCheckBox(self.frame3)
        self.cb_13789.setGeometry(QtCore.QRect(150, 80, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_13789.setFont(font)
        self.cb_13789.setObjectName(_fromUtf8("cb_13789"))
        self.cb_170 = QtGui.QCheckBox(self.frame3)
        self.cb_170.setGeometry(QtCore.QRect(150, 100, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_170.setFont(font)
        self.cb_170.setObjectName(_fromUtf8("cb_170"))
        self.cb_1237 = QtGui.QCheckBox(self.frame3)
        self.cb_1237.setGeometry(QtCore.QRect(150, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_1237.setFont(font)
        self.cb_1237.setObjectName(_fromUtf8("cb_1237"))
        self.cb_74 = QtGui.QCheckBox(self.frame3)
        self.cb_74.setGeometry(QtCore.QRect(150, 140, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_74.setFont(font)
        self.cb_74.setObjectName(_fromUtf8("cb_74"))
        self.cb_55889 = QtGui.QCheckBox(self.frame3)
        self.cb_55889.setGeometry(QtCore.QRect(150, 160, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_55889.setFont(font)
        self.cb_55889.setObjectName(_fromUtf8("cb_55889"))
        self.cb_55890 = QtGui.QCheckBox(self.frame3)
        self.cb_55890.setGeometry(QtCore.QRect(300, 60, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_55890.setFont(font)
        self.cb_55890.setObjectName(_fromUtf8("cb_55890"))
        self.cb_336 = QtGui.QCheckBox(self.frame3)
        self.cb_336.setGeometry(QtCore.QRect(300, 80, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_336.setFont(font)
        self.cb_336.setObjectName(_fromUtf8("cb_336"))
        self.cb_798 = QtGui.QCheckBox(self.frame3)
        self.cb_798.setGeometry(QtCore.QRect(300, 100, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_798.setFont(font)
        self.cb_798.setObjectName(_fromUtf8("cb_798"))
        self.cb_2105 = QtGui.QCheckBox(self.frame3)
        self.cb_2105.setGeometry(QtCore.QRect(300, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_2105.setFont(font)
        self.cb_2105.setObjectName(_fromUtf8("cb_2105"))
        self.cb_2030 = QtGui.QCheckBox(self.frame3)
        self.cb_2030.setGeometry(QtCore.QRect(300, 140, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_2030.setFont(font)
        self.cb_2030.setObjectName(_fromUtf8("cb_2030"))
        self.cb_517 = QtGui.QCheckBox(self.frame3)
        self.cb_517.setGeometry(QtCore.QRect(300, 160, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_517.setFont(font)
        self.cb_517.setObjectName(_fromUtf8("cb_517"))
        self.cb_1137 = QtGui.QCheckBox(self.frame3)
        self.cb_1137.setGeometry(QtCore.QRect(10, 180, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_1137.setFont(font)
        self.cb_1137.setObjectName(_fromUtf8("cb_1137"))
        self.cb_1322 = QtGui.QCheckBox(self.frame3)
        self.cb_1322.setGeometry(QtCore.QRect(10, 200, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_1322.setFont(font)
        self.cb_1322.setObjectName(_fromUtf8("cb_1322"))
        self.cb_8257 = QtGui.QCheckBox(self.frame3)
        self.cb_8257.setGeometry(QtCore.QRect(150, 180, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_8257.setFont(font)
        self.cb_8257.setObjectName(_fromUtf8("cb_8257"))
        self.cb_1383 = QtGui.QCheckBox(self.frame3)
        self.cb_1383.setGeometry(QtCore.QRect(300, 180, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_1383.setFont(font)
        self.cb_1383.setObjectName(_fromUtf8("cb_1383"))
        self.cb_50245 = QtGui.QCheckBox(self.frame3)
        self.cb_50245.setGeometry(QtCore.QRect(150, 200, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(10)
        self.cb_50245.setFont(font)
        self.cb_50245.setObjectName(_fromUtf8("cb_50245"))
        self.frame4 = QtGui.QFrame(Dialog)
        self.frame4.setGeometry(QtCore.QRect(10, 620, 431, 201))
        self.frame4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame4.setObjectName(_fromUtf8("frame4"))
        self.progressBar = QtGui.QProgressBar(self.frame4)
        self.progressBar.setGeometry(QtCore.QRect(0, 150, 431, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.btn_start = QtGui.QPushButton(self.frame4)
        self.btn_start.setGeometry(QtCore.QRect(100, 170, 101, 31))
        self.btn_start.setObjectName(_fromUtf8("btn_start"))
        self.btn_exit = QtGui.QPushButton(self.frame4)
        self.btn_exit.setGeometry(QtCore.QRect(230, 170, 101, 31))
        self.btn_exit.setObjectName(_fromUtf8("btn_exit"))
        self.textEdit = QtGui.QTextEdit(self.frame4)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 431, 141))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.frame1 = QtGui.QFrame(Dialog)
        self.frame1.setGeometry(QtCore.QRect(10, 10, 431, 121))
        self.frame1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame1.setObjectName(_fromUtf8("frame1"))
        self.label1 = QtGui.QLabel(self.frame1)
        self.label1.setGeometry(QtCore.QRect(180, 0, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rix모던고딕 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.factor1 = QtGui.QLineEdit(self.frame1)
        self.factor1.setGeometry(QtCore.QRect(80, 30, 51, 16))
        self.factor1.setObjectName(_fromUtf8("factor1"))
        self.label1_1 = QtGui.QLabel(self.frame1)
        self.label1_1.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label1_1.setObjectName(_fromUtf8("label1_1"))
        self.label1_2 = QtGui.QLabel(self.frame1)
        self.label1_2.setGeometry(QtCore.QRect(140, 30, 71, 16))
        self.label1_2.setObjectName(_fromUtf8("label1_2"))
        self.factor2 = QtGui.QLineEdit(self.frame1)
        self.factor2.setGeometry(QtCore.QRect(220, 30, 51, 16))
        self.factor2.setObjectName(_fromUtf8("factor2"))
        self.label1_3 = QtGui.QLabel(self.frame1)
        self.label1_3.setGeometry(QtCore.QRect(140, 60, 71, 16))
        self.label1_3.setObjectName(_fromUtf8("label1_3"))
        self.factor3 = QtGui.QLineEdit(self.frame1)
        self.factor3.setGeometry(QtCore.QRect(220, 60, 51, 16))
        self.factor3.setObjectName(_fromUtf8("factor3"))
        self.label1_4 = QtGui.QLabel(self.frame1)
        self.label1_4.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.label1_4.setObjectName(_fromUtf8("label1_4"))
        self.factor1_2 = QtGui.QLineEdit(self.frame1)
        self.factor1_2.setGeometry(QtCore.QRect(80, 60, 51, 16))
        self.factor1_2.setObjectName(_fromUtf8("factor1_2"))
        self.label1_5 = QtGui.QLabel(self.frame1)
        self.label1_5.setGeometry(QtCore.QRect(290, 30, 131, 51))
        self.label1_5.setObjectName(_fromUtf8("label1_5"))
        self.comboBox = QtGui.QComboBox(self.frame1)
        self.comboBox.setGeometry(QtCore.QRect(90, 90, 161, 21))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.label1_6 = QtGui.QLabel(self.frame1)
        self.label1_6.setGeometry(QtCore.QRect(10, 90, 81, 16))
        self.label1_6.setObjectName(_fromUtf8("label1_6"))
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 130, 431, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Aladin", None))
        self.label2.setText(_translate("Dialog", "지점 선택", None))
        self.cb_sinsa.setText(_translate("Dialog", "가로수길점", None))
        self.cb_gangnam.setText(_translate("Dialog", "강남점", None))
        self.cb_geondae.setText(_translate("Dialog", "건대점", None))
        self.cb_nowon.setText(_translate("Dialog", "노원점", None))
        self.cb_daehakro.setText(_translate("Dialog", "대학로점", None))
        self.cb_suyu.setText(_translate("Dialog", "수유점", None))
        self.cb_sillim.setText(_translate("Dialog", "신림점", None))
        self.cb_sinchon.setText(_translate("Dialog", "신촌점", None))
        self.cb_yeonsinnae.setText(_translate("Dialog", "연신내점", None))
        self.cb_jamsil.setText(_translate("Dialog", "잠실롯데월드타워점", None))
        self.cb_sincheon.setText(_translate("Dialog", "잠실신천점", None))
        self.cb_ilsan.setText(_translate("Dialog", "일산점", None))
        self.cb_dongbo.setText(_translate("Dialog", "부산서면점", None))
        self.cb_jongno.setText(_translate("Dialog", "종로점", None))
        self.cb_hapjeong.setText(_translate("Dialog", "합정점", None))
        self.cb_dongtan.setText(_translate("Dialog", "동탄점", None))
        self.cb_bucheon.setText(_translate("Dialog", "부천점", None))
        self.cb_bundang.setText(_translate("Dialog", "분당서현점", None))
        self.cb_yatap.setText(_translate("Dialog", "분당야탑점", None))
        self.cb_sanbon.setText(_translate("Dialog", "산본점", None))
        self.cb_suwon.setText(_translate("Dialog", "수원점", None))
        self.cb_hwajeong.setText(_translate("Dialog", "화정점", None))
        self.cb_sangmu.setText(_translate("Dialog", "광주상무점", None))
        self.cb_gwangju.setText(_translate("Dialog", "광주충장로점", None))
        self.cb_daegu.setText(_translate("Dialog", "대구동성로점", None))
        self.cb_sangin.setText(_translate("Dialog", "대구상인점", None))
        self.cb_daejeoncityhall.setText(_translate("Dialog", "대전시청역점", None))
        self.cb_daejeon.setText(_translate("Dialog", "대전은행점", None))
        self.cb_killy.setText(_translate("Dialog", "부산경성대부경대역점", None))
        self.cb_centum.setText(_translate("Dialog", "부산센텀점", None))
        self.cb_ulsan.setText(_translate("Dialog", "울산점", None))
        self.cb_gyesan.setText(_translate("Dialog", "인천계산홈플러스점", None))
        self.cb_jeonju.setText(_translate("Dialog", "전주점", None))
        self.cb_cheonan.setText(_translate("Dialog", "천안점", None))
        self.cb_cheongju.setText(_translate("Dialog", "청주점", None))
        self.cb_guwol.setText(_translate("Dialog", "인천구월점", None))
        self.cb_deokcheon.setText(_translate("Dialog", "부산덕천점", None))
        self.cb_buksuwon.setText(_translate("Dialog", "북수원홈플러스점", None))
        self.label3.setText(_translate("Dialog", "카테고리 선택", None))
        self.cb_1230.setText(_translate("Dialog", "가정/요리/뷰티", None))
        self.cb_2551.setText(_translate("Dialog", "만화", None))
        self.cb_1108.setText(_translate("Dialog", "어린이", None))
        self.cb_656.setText(_translate("Dialog", "인문학", None))
        self.cb_4395.setText(_translate("Dialog", "사전/기타", None))
        self.cb_351.setText(_translate("Dialog", "컴퓨터", None))
        self.cb_1196.setText(_translate("Dialog", "여행", None))
        self.cb_1.setText(_translate("Dialog", "소설/시/희곡", None))
        self.cb_987.setText(_translate("Dialog", "과학", None))
        self.cb_50246.setText(_translate("Dialog", "초등참고서", None))
        self.cb_13789.setText(_translate("Dialog", "유아", None))
        self.cb_170.setText(_translate("Dialog", "경제경영", None))
        self.cb_1237.setText(_translate("Dialog", "종교/역학", None))
        self.cb_74.setText(_translate("Dialog", "역사", None))
        self.cb_55889.setText(_translate("Dialog", "에세이", None))
        self.cb_55890.setText(_translate("Dialog", "건강/취미/레저", None))
        self.cb_336.setText(_translate("Dialog", "자기계발", None))
        self.cb_798.setText(_translate("Dialog", "사회과학", None))
        self.cb_2105.setText(_translate("Dialog", "고전", None))
        self.cb_2030.setText(_translate("Dialog", "좋은부모", None))
        self.cb_517.setText(_translate("Dialog", "예술/대중문화", None))
        self.cb_1137.setText(_translate("Dialog", "청소년", None))
        self.cb_1322.setText(_translate("Dialog", "외국어", None))
        self.cb_8257.setText(_translate("Dialog", "대학교재/전문서적", None))
        self.cb_1383.setText(_translate("Dialog", "수험서/자격증", None))
        self.cb_50245.setText(_translate("Dialog", "중/고등참고서", None))
        self.btn_start.setText(_translate("Dialog", "시작", None))
        self.btn_exit.setText(_translate("Dialog", "종료", None))
        self.label1.setText(_translate("Dialog", "옵션 설정", None))
        self.label1_1.setText(_translate("Dialog", "가격변환율", None))
        self.label1_2.setText(_translate("Dialog", "정가대비최대", None))
        self.label1_3.setText(_translate("Dialog", "정가대비최소", None))
        self.label1_4.setText(_translate("Dialog", "최저보장가", None))
        self.label1_5.setText(_translate("Dialog", " 가격변환율 ex) 3.0 \n"
" 정가대비 ex) 80% \n"
" 최저보장가 ex) 7000", None))
        self.label1_6.setText(_translate("Dialog", "멀티프로세싱", None))

